[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
# serialization
log = "0.4.0"

##powdr =         { git = "https://github.com/0xEigenLabs/powdr", branch = "eigen/v1", default-features = false }
powdr =              { path = "../../powdr/powdr", default-features = false }
starky =         { path = "../starky" }
recursion =  { path = "../recursion" }

hex = "0.4.3"
thiserror = "1.0"
serde_json = "1.0.108"
anyhow = "1.0.79"
bincode = "1.3.3"

[dev-dependencies]
env_logger = "0.10"
num-traits = "0.2.17"

[features]
default = []
#avx512 = ["starky/avx512", "recursion/avx512", "powdr/starky-avx512"]
avx512 = ["starky/avx512", "recursion/avx512"]
